// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SacramentPlanner.Models;
using System;

namespace SacramentPlanner.Migrations
{
    [DbContext(typeof(SacramentPlannerContext))]
    [Migration("20180405202350_RegEx")]
    partial class RegEx
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentPlanner.Models.Meeting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClosePrayer")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CloseSong")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CloseSongNum");

                    b.Property<string>("Conduct")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date");

                    b.Property<string>("OpenPrayer")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OpenSong")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("OpenSongNum");

                    b.Property<string>("SacSong")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SacSongNum");

                    b.Property<string>("SecondSpeaker");

                    b.Property<string>("SecondTopic");

                    b.Property<string>("ThirdSpeaker");

                    b.Property<string>("ThirdTopic");

                    b.Property<string>("YouthSpeaker");

                    b.Property<string>("YouthTopic");

                    b.HasKey("ID");

                    b.ToTable("Meeting");
                });
#pragma warning restore 612, 618
        }
    }
}
